# Generated by Django 3.0.8 on 2020-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('Vote1', models.PositiveIntegerField(default=0)),
                ('Vote2', models.PositiveIntegerField(default=0)),
                ('Vote3', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
