# Generated by Django 3.0.8 on 2020-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='Opt1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='Opt2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='Opt3',
            field=models.CharField(default='', max_length=20),
        ),
    ]
